"""utils.transcript

Robust YouTube transcript extraction using youtube-transcript-api.

Key goals:
- Handle many YouTube URL formats (watch, youtu.be, embed, shorts, mobile, etc.)
- Prefer manual captions, then autogenerated captions
- Detect/try available languages when possible
- Retry transient network errors
- Return clean transcript text
- Provide detailed structured error information
"""

from __future__ import annotations

import logging
import re
import time
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import parse_qs, urlparse


from youtube_transcript_api import (  # type: ignore
    CouldNotRetrieveTranscript,
    NoTranscriptFound,
    TranscriptsDisabled,
    VideoUnavailable,
    YouTubeTranscriptApi,
)

logger = logging.getLogger(__name__)


# -------------------------
# Video id extraction
# -------------------------

_YT_WATCH_RE = re.compile(r"(?:youtube\.com)/(?:watch)\?v=([^&\n?#]+)")
_YT_SHORTS_RE = re.compile(r"(?:youtube\.com)/(?:shorts)/([^&\n?#]+)")
_YT_EMBED_RE = re.compile(r"(?:youtube\.com)/(?:embed)/([^&\n?#]+)")
_YT_V_RE = re.compile(r"(?:youtube\.com)/v/([^&\n?#]+)")
_YT_YTBE_RE = re.compile(r"(?:youtu\.be)/([^&\n?#]+)")


def extract_video_id(url: str) -> Optional[str]:
    """Extract a YouTube video id from multiple common URL formats.

    Supports:
    - https://www.youtube.com/watch?v=...
    - https://m.youtube.com/watch?v=...
    - https://youtu.be/...
    - https://youtube.com/embed/...
    - https://www.youtube.com/shorts/...
    - https://www.youtube.com/v/...

    Returns None if it can't reliably determine the ID.
    """
    if not url or not isinstance(url, str):
        logger.warning("Invalid URL type for extract_video_id: %s", type(url))
        return None

    url = url.strip()

    # Normalize missing scheme/host cases (best-effort)
    if url.startswith("//"):
        url = "https:" + url

    # Strip common tracking params by focusing on path/query patterns.
    for rx in (_YT_WATCH_RE, _YT_SHORTS_RE, _YT_EMBED_RE, _YT_V_RE, _YT_YTBE_RE):
        m = rx.search(url)

        if m:
            video_id = (m.group(1) or "").strip()
            return video_id or None

    # Fallback: parse query params (watch?v=...)
    try:
        parsed = urlparse(url)
        qs = parse_qs(parsed.query)
        v = (qs.get("v") or [None])[0]
        if v:
            return v.strip() or None
    except Exception:
        pass

    # Final fallback: sometimes embed/shorts are provided without the full host
    # e.g. "youtube.com/watch?v=..." or "youtu.be/..."
    try:
        m = re.search(r"(?:v=|/)([0-9A-Za-z_-]{11})", url)
        if m:
            return m.group(1)
    except Exception:
        pass

    logger.warning("Could not extract video ID from URL: %s", url)
    return None



# -------------------------
# Transcript extraction
# -------------------------


@dataclass
class TranscriptResult:
    text: Optional[str]
    error: Optional[Dict[str, Any]]


_TRANSIENT_ERROR_HINTS = (
    "timed out",
    "timeout",
    "Temporary failure",
    "Connection aborted",
    "Connection reset",
    "Read timed out",
)


def _clean_transcript_text(text: str) -> str:
    # youtube-transcript-api returns individual caption lines; we join and normalize spaces.
    text = re.sub(r"\s+", " ", text or "").strip()
    return text


def _looks_transient(e: Exception) -> bool:
    msg = str(e).lower()
    return any(h in msg for h in _TRANSIENT_ERROR_HINTS)


def _try_extract_from_transcript_object(
    transcripts: Any,
    preferred_languages: List[str],
) -> Tuple[Optional[str], Optional[Dict[str, Any]]]:
    """Try captions from a list/transcripts object.

    We attempt:
    1) manually created captions for preferred languages
    2) autogenerated captions for preferred languages
    3) any language (manual then autogenerated)
    """

    attempted: List[Dict[str, Any]] = []

    def attempt_for_lang(lang: str, manual: bool) -> Optional[str]:
        nonlocal attempted
        try:
            # youtube-transcript-api API:
            # transcripts object from list_transcripts(video_id)
            # - get_transcript(language_code) can return transcript (prefers manual by default)
            # - There is also get_transcript(language_code) on transcript collection.
            # - Autogenerated vs manual is handled by available transcript entries.
            # We'll use transcript_list.find_manually_created_transcript / find_generated_transcript.
            # Not all versions support both methods, so we try defensively.

            if manual and hasattr(transcripts, "find_manually_created_transcript"):
                tr = transcripts.find_manually_created_transcript([lang])
            elif (not manual) and hasattr(transcripts, "find_generated_transcript"):
                tr = transcripts.find_generated_transcript([lang])
            else:
                # fallback: get_transcript
                tr = transcripts.get_transcript(lang)

            data = tr.fetch()
            attempted.append({"language": lang, "source": "manual" if manual else "generated", "ok": True})
            joined = " ".join([entry.get("text", "") for entry in data])
            joined = _clean_transcript_text(joined)
            return joined if joined and len(joined.split()) >= 5 else None
        except Exception as ex:
            attempted.append({
                "language": lang,
                "source": "manual" if manual else "generated",
                "ok": False,
                "error": type(ex).__name__,
                "detail": str(ex),
            })
            return None

    # Preferred language order
    for lang in preferred_languages:
        text = attempt_for_lang(lang, manual=True)
        if text:
            return text, None

    for lang in preferred_languages:
        text = attempt_for_lang(lang, manual=False)
        if text:
            return text, None

    # Any available language (manual then generated)
    # We can get available languages by introspecting transcripts.
    available_langs: List[str] = []
    try:
        if hasattr(transcripts, "manual_language_codes"):
            available_langs.extend(list(transcripts.manual_language_codes))
        if hasattr(transcripts, "generated_language_codes"):
            available_langs.extend(list(transcripts.generated_language_codes))
        # fallback: probe commonly used languages in one go
    except Exception:
        pass

    # If we couldn't infer, just try English first then given preferred list then any
    probe_langs = []
    for x in ["en", *preferred_languages, *available_langs]:
        if x and x not in probe_langs:
            probe_langs.append(x)

    for lang in probe_langs:
        text = attempt_for_lang(lang, manual=True)
        if text:
            return text, None

    for lang in probe_langs:
        text = attempt_for_lang(lang, manual=False)
        if text:
            return text, None

    err = {
        "type": "TranscriptNotFound",
        "message": "No transcript could be retrieved from any tried language/source.",
        "attempted": attempted,
    }
    return None, err


def get_transcript(
    url: str,
    languages: Optional[List[str]] = None,
    retry: int = 2,
    retry_backoff_seconds: float = 1.5,
) -> Optional[str]:
    """Get transcript text.

    Returns:
      - transcript text if available
      - None if unavailable

    For detailed error logging, check app.log; app.py only currently needs the text,
    but we keep richer logging inside.
    """

    if languages is None:
        languages = ["en", "es", "fr", "de"]

    video_id = extract_video_id(url)
    if not video_id:
        return None

    last_err: Optional[Exception] = None

    for attempt in range(retry + 1):
        try:
            logger.info("Fetching transcript (attempt %s/%s) video_id=%s", attempt + 1, retry + 1, video_id)

            transcripts = YouTubeTranscriptApi.list_transcripts(video_id)

            # Try languages and sources.
            text, err = _try_extract_from_transcript_object(transcripts, preferred_languages=languages)
            if text:
                logger.info("Transcript extracted successfully video_id=%s length_chars=%s", video_id, len(text))
                logger.info("Transcript language preference tried=%s", languages)
                return text

            # If we reach here, extraction failed.
            logger.warning("Transcript not found for video_id=%s err=%s", video_id, err)
            return None

        except (TranscriptsDisabled, NoTranscriptFound, VideoUnavailable, CouldNotRetrieveTranscript) as ex:
            # These are not reliably solvable by retry; but we still record and allow retry for network-ish.
            last_err = ex
            logger.warning("Transcript retrieval failed video_id=%s type=%s detail=%s", video_id, type(ex).__name__, ex)
            if isinstance(ex, (TranscriptsDisabled, NoTranscriptFound, VideoUnavailable, CouldNotRetrieveTranscript)):
                # Give up early: retry likely won't help for these.
                break

        except Exception as ex:
            last_err = ex
            logger.error("Unexpected transcript error video_id=%s attempt=%s err=%s", video_id, attempt + 1, ex)
            if attempt < retry and _looks_transient(ex):
                time.sleep(retry_backoff_seconds * (attempt + 1))
                continue
            break

    logger.error("All transcript attempts failed video_id=%s last_error=%s", video_id, last_err)
    return None


def get_available_transcripts(url: str) -> Optional[Dict[str, Any]]:
    """Return available languages for a video (manual + generated if possible)."""
    video_id = extract_video_id(url)
    if not video_id:
        return None

    try:
        transcripts = YouTubeTranscriptApi.list_transcripts(video_id)
        manual_langs: List[str] = []
        generated_langs: List[str] = []

        # youtube-transcript-api versions differ; use best-effort introspection
        for attr, dest in [
            ("manual_language_codes", manual_langs),
            ("generated_language_codes", generated_langs),
        ]:
            if hasattr(transcripts, attr):
                try:
                    dest.extend(list(getattr(transcripts, attr)))
                except Exception:
                    pass

        # Some versions might not expose these; fall back to trying list_transcripts('en') usage is not reliable.
        languages = sorted(set(manual_langs + generated_langs))
        return {"video_id": video_id, "available_languages": languages, "manual": manual_langs, "generated": generated_langs}

    except Exception as ex:
        logger.error("Error listing available transcripts video_id=%s err=%s", video_id, ex)
        return None

